name: WakaTime - Readme

on:
  schedule:
    # Runs at 12 am  '0 0 * * *'  UTC
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Update the WakaTime Stat
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@v0.1.7
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          BRANCH: "master"
          COMMIT_MSG: "Automated Coding Activity Update :alien:"
          # Range of fetching data - default is "last_7_days". See https://wakatime.com/developers#stats for more options
          STATS_RANGE: "last_7_days"
